CREATE TABLE community_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('builder', 'backer', 'investor')),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  organization TEXT,
  country TEXT,
  interest_area TEXT,
  message TEXT,
  source_page TEXT,
  follow_up_status TEXT NOT NULL DEFAULT 'new' CHECK (
    follow_up_status IN ('new', 'contacted', 'qualified', 'archived')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX community_signups_role_idx ON community_signups (role);
CREATE INDEX community_signups_follow_up_status_idx ON community_signups (follow_up_status);
CREATE INDEX community_signups_created_at_idx ON community_signups (created_at DESC);
